# Usamos una imagen base de OpenJDK
FROM openjdk:11-jre-slim

# Establecemos el directorio de trabajo en /app
WORKDIR /app

# Copiamos el archivo JAR de tu aplicación al contenedor
COPY target/tu-aplicacion.jar tu-aplicacion.jar

# Exponemos el puerto en el que se ejecutará la aplicación Spring Boot
EXPOSE 8080

# Comando para ejecutar la aplicación Spring Boot
CMD ["java", "-jar", "ApiPostgressApplication.jar"]
