spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:59466/railway
    username: postgres
    password: ssiKbirxwooPsqosorVajhnkeudlxCAu
    name: api-fivedrive

  sql:
    init:
      mode: always