management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: api-fivedrive
    description: A blog with articles about The Spring Framework.
    author: Andres Cuello
    version: '4'
spring:
  profiles:
    active: dev